/*  File generated by StatWeave  */
display "--- Ou" "tput file from StatWeave, engine = StataEngine ---"

/* ---- Chunk 1: "01-data-io-1-Stata" ----- */
set scheme s1mono

/* ---- Chunk 4: "01-data-io-4-Stata" ----- */
sysuse auto

/* ---- Chunk 5: "01-data-io-5-Stata" ----- */
describe, short

/* ---- Chunk 6: "01-data-io-6-Stata" ----- */
list make-length in 1/2

/* ---- Chunk 7: "01-data-io-7-Stata" ----- */
webuse lbw  

/* ---- Chunk 8: "01-data-io-8-Stata" ----- */
describe, short

/* ---- Chunk 9: "01-data-io-9-Stata" ----- */
list in 1/2

/* ---- Chunk 12: "01-data-io-12-Stata" ----- */
webuse lbw
summarize bwt  

/* ---- Chunk 13: "01-data-io-13-Stata" ----- */
format bwt %4.2f
summarize bwt, format  

/* ---- Chunk 15: "01-data-io-15-Stata" ----- */
su b

/* ---- Chunk 16: "01-data-io-16-Stata" ----- */
describe, simple  

/* ---- Chunk 17: "01-data-io-17-Stata" ----- */
summarize bwt lwt

/* ---- Chunk 18: "01-data-io-18-Stata" ----- */
summarize low-lwt

/* ---- Chunk 19: "01-data-io-19-Stata" ----- */
summarize bwt lwt in 1/5 

/* ---- Chunk 20: "01-data-io-20-Stata" ----- */
list id bwt lwt in 1/5  

/* ---- Chunk 21: "01-data-io-21-Stata" ----- */
summarize bwt lwt if ui == 0 

/* ---- Chunk 22: "01-data-io-22-Stata" ----- */
tabulate ui

/* ---- Chunk 23: "01-data-io-23-Stata" ----- */
by ui, sort: summarize bwt lwt  

/* ---- Chunk 24: "01-data-io-24-Stata" ----- */
cd ~/Documents/git/RITME/IAE/data  

/* ---- Chunk 25: "01-data-io-25-Stata" ----- */
import delimited "birthwt.csv", delimiter(comma) varnames(1) clear  

/* ---- Chunk 26: "01-data-io-26-Stata" ----- */
infile low age lwt race smoke ptl ht ui ftv bwt using "birthwt.dat", clear  

/* ---- Chunk 30: "01-data-io-30-Stata" ----- */
webuse lbw, clear
codebook, compact    

/* ---- Chunk 31: "01-data-io-31-Stata" ----- */
codebook race

/* ---- Chunk 32: "01-data-io-32-Stata" ----- */
import delimited "birthwt.csv", delimiter(comma) varnames(1) clear  
codebook, compact

/* ---- Chunk 33: "01-data-io-33-Stata" ----- */
label data "Hosmer & Lemeshow data"
note: Mise en forme des données lbw
label define lrace 1 "white" 2 "black" 3 "other"
label values race lrace
label variable race "ethnicity"
label list

/* ---- Chunk 34: "01-data-io-34-Stata" ----- */
codebook, compact

/* ---- Chunk 35: "01-data-io-35-Stata" ----- */
sort bwt
sort smoke bwt
gsort -ftv bwt
list in 1/3
