/*  File generated by StatWeave  */
display "--- Ou" "tput file from StatWeave, engine = StataEngine ---"

/* ---- Chunk 1: "03-tests-1-Stata" ----- */
set scheme lean2

/* ---- Chunk 2: "03-tests-2-Stata" ----- */
use data/gsoep09

/* ---- Chunk 3: "03-tests-3-Stata" ----- */
gen age = 2009 - ybirth
mvdecode income, mv(0=.c)

/* ---- Chunk 4: "03-tests-4-Stata" ----- */
gen lincome = log(income)  

/* ---- Chunk 5: "03-tests-5-Stata" ----- */
bysort sex: summarize lincome  

/* ---- Chunk 6: "03-tests-6-Stata" ----- */
graph box lincome, over(sex) ytitle("Income (log(2)")   

/* ---- Chunk 7: "03-tests-7-Stata" ----- */
ttest lincome, by(sex)

/* ---- Chunk 8: "03-tests-8-Stata" ----- */
ttest lincome, by(sex) welch

/* ---- Chunk 9: "03-tests-9-Stata" ----- */
bysort sex: ci lincome

/* ---- Chunk 10: "03-tests-10-Stata" ----- */
mean lincome if sex == 1

/* ---- Chunk 11: "03-tests-11-Stata" ----- */
local zc = 1-invnormal(0.95)
display 10.08129 - `zc'/2 * .0259338 

/* ---- Chunk 12: "03-tests-12-Stata" ----- */
display 10.08129 - invt(1745, 0.975) * .0259338  

/* ---- Chunk 13: "03-tests-13-Stata" ----- */
ranksum lincome, by(sex)  

/* ---- Chunk 14: "03-tests-14-Stata" ----- */
recode egp (1/2=1) (3/5=2) (8/9=3) (15/18=.), gen(egp4)
label define egp4 1 "Service class 1/2" 2 "Non-manuals & self-employed" 3 "Manuals"
label values egp4 egp4

/* ---- Chunk 15: "03-tests-15-Stata" ----- */
histogram lincome, by(egp4, col(3)) freq  

/* ---- Chunk 16: "03-tests-16-Stata" ----- */
twoway (kdensity lincome), by(egp4)    

/* ---- Chunk 17: "03-tests-17-Stata" ----- */
graph box lincome, over(egp4) ytitle("Income (log(2)")   

/* ---- Chunk 18: "03-tests-18-Stata" ----- */
tabstat lincome, by(egp4) stats(mean sd count)

/* ---- Chunk 19: "03-tests-19-Stata" ----- */
oneway lincome egp4    

/* ---- Chunk 20: "03-tests-20-Stata" ----- */
quietly: anova lincome egp4
predict r, resid 
qnorm r   

/* ---- Chunk 21: "03-tests-21-Stata" ----- */
robvar lincome, by(egp4)

/* ---- Chunk 22: "03-tests-22-Stata" ----- */
oneway lincome egp4, bonferroni noanova

/* ---- Chunk 23: "03-tests-23-Stata" ----- */
quietly: ttest lincome if egp4 != 1, by(egp4)
display r(p)*3

/* ---- Chunk 24: "03-tests-24-Stata" ----- */
anova lincome egp4

/* ---- Chunk 25: "03-tests-25-Stata" ----- */
pwcompare egp4, cformat(%3.2f)

/* ---- Chunk 26: "03-tests-26-Stata" ----- */
generate sexb = sex - 1
tabulate sexb  

/* ---- Chunk 27: "03-tests-27-Stata" ----- */
bitest sexb == 0.5    

/* ---- Chunk 28: "03-tests-28-Stata" ----- */
ci sexb, binomial  

/* ---- Chunk 29: "03-tests-29-Stata" ----- */
prtest sexb == 0.5    

/* ---- Chunk 30: "03-tests-30-Stata" ----- */
generate egpb = egp4 == 1
prtest egpb, by(sexb)

/* ---- Chunk 32: "03-tests-32-Stata" ----- */
tabulate sex egp4  

/* ---- Chunk 33: "03-tests-33-Stata" ----- */
tabulate sex egp4, row

/* ---- Chunk 34: "03-tests-34-Stata" ----- */
tabulate sex egp4, chi

/* ---- Chunk 35: "03-tests-35-Stata" ----- */
tabulate sex egp4, expected

/* ---- Chunk 36: "03-tests-36-Stata" ----- */
tabulate sex egp4, exact

/* ---- Chunk 37: "03-tests-37-Stata" ----- */
clear all
webuse lbw  

/* ---- Chunk 38: "03-tests-38-Stata" ----- */
list in 1/5  

/* ---- Chunk 39: "03-tests-39-Stata" ----- */
tabodds low smoke, or     

/* ---- Chunk 40: "03-tests-40-Stata" ----- */
cc low smoke, woolf  

/* ---- Chunk 41: "03-tests-41-Stata" ----- */
cs low smoke
